services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_management && rabbitmqctl set_policy ha-all \"\" '{\"ha-mode\":\"all\"}'"
